### Get All users

GET http://localhost:8080/admin/users

### fetch user

GET http://localhost:8080/admin/user/9

### Delete User By Id 
DELETE http://localhost:8080/admin/user/

### update User 
PUT http://localhost:8080/admin/user/update HTTP/1.1 
content-type: application/json

{  
  
 "id": 9,
 "userName" : "rueben", 
 "email" : "ally@gmail.com",
 "password": "abcd", 
 "currentLocation" : "jaipur",
 "role": "admin"
    

}
### create Booking slot

POST http://localhost:8080/admin/create/bookingslot HTTP/1.1 
content-type: application/json

{

  "location": "pune",
  "startDate": "2023-06-04",
  "endDate": "2023-07-11",
  "startingTime": "23:00",
  "endingTime": "05:00",
  "price": 1010.0,
  "airConditioning": "yes",
  "noOfStops": 4,
  "serviceAvailable": "yes"

}

### Get all Booking slots

GET http://localhost:8080/admin/bookingslot

### Get all Booking slots by location

GET http://localhost:8080/admin/filterLocation?location=kolkata


### Fetch booking slot

GET http://localhost:8080/admin/booking/23


### delete Booking slot

DELETE http://localhost:8080/admin/bookingslot/18

### update User 
PUT http://localhost:8080/admin/bookingslot/update HTTP/1.1 
content-type: application/json

{
  "id": 21,
  "location": "agra",
  "startDate": "2023-05-04",
  "endDate": "2023-05-11",
  "startingTime": "13:00",
  "endingTime": "15:00",
  "price": 101.0,
  "airConditioning": "yes",
  "noOfStops": 4,
  "serviceAvailable": "yes"


}

### Get all userBooking 

GET http://localhost:8080/admin/alluserbookings

### Get all userBooking for specific user by username

GET http://localhost:8080/admin/alluserbookings/rueben

