### Create New Account

POST http://localhost:8080/login/create HTTP/1.1 
content-type: application/json

{
    "userName" : "pqr", 
    "email" : "tom@gmail.com", 
    "password" : "abcd", 
    "currentLocation" : "delhi",
    "role" : "user"
}

### login
POST http://localhost:8080/login/ HTTP/1.1 
content-type: application/json

{
   
    "email": "tom@gmail.com", 
    "password" : "abcd" 
   
}

### forgot password
POST http://localhost:8080/login/forgotpassword HTTP/1.1 
content-type: application/json

{
   "email": "tom@gmail.com"
}