
### Get user 

GET http://localhost:8080/user/12


### Create New user booking 

POST http://localhost:8080/user/createbookingslot HTTP/1.1 
content-type: application/json

{
     "location": "delhi",
      "startDate": "2023-06-04",
      "endDate": "2023-07-11",
      "startingTime": "23:00:00",
      "endingTime": "05:00:00",
      "price": 1010.0,
      "airConditioning": "no",
      "noOfStops": 4,
      "serviceAvailable": "yes",
      "userId": 12


}

### Get All user bookings

GET http://localhost:8080/user/userbooking/12

### delete Booking slot

DELETE http://localhost:8080/user/12/booking/28

### Create New user feedback 

POST http://localhost:8080/user/feedback/12 HTTP/1.1 
content-type: application/json

{

    "userId": 12,
    "comment": "it is working bad",
    "rating": 10

}

### Get All feedbacks

GET http://localhost:8080/user/feedback
