### Create New user booking 

POST http://localhost:8080/user/createbookingslot HTTP/1.1 
content-type: application/json

{

  "location": "New York",
  "startDate": "2023-05-05",
  "endDate": "2023-05-10",
  "startingTime": "14:00",
  "endingTime": "17:00",
  "price": 100.0,
  "userId": 2


}